{
 "type": "record",
 "name": "StockTickEvent",
 "namespace": "finstream.market",
 "fields": [
  { "name": "event_id", "type": "string" },
  { "name": "event_time", "type": "long" },
  { "name": "symbol", "type": "string" },
  { "name": "price", "type": "double" },
  { "name": "open_price", "type": ["null", "double"], "default": null },
  { "name": "high_price", "type": ["null", "double"], "default": null },
  { "name": "low_price", "type": ["null", "double"], "default": null },
  { "name": "close_price", "type": ["null", "double"], "default": null },
  { "name": "volume", "type": ["null", "double"], "default": null },
  { "name": "source", "type": "string" },
  { "name": "raw_payload", "type": "string" }
 ]
}
