{
  "type": "record",
  "name": "TransactionEvent",
  "namespace": "finstream.transactions",
  "fields": [
    { "name": "event_id", "type": "string" },
    { "name": "transaction_id", "type": "string" },

    { "name": "event_time", "type": "string" },
    { "name": "ingestion_time", "type": "string" },
    { "name": "source", "type": "string", "default": "ieee_cis" },

    { "name": "split", "type": "string", "default": "train" },
    { "name": "transaction_dt", "type": "long" },

    { "name": "amount", "type": "double" },
    { "name": "currency", "type": "string", "default": "USD" },
    { "name": "product_cd", "type": ["null", "string"], "default": null },

    { "name": "customer_id", "type": "string" },
    { "name": "card_id", "type": "string" },
    { "name": "merchant_id", "type": "string" },

    { "name": "card_brand", "type": ["null", "string"], "default": null },
    { "name": "card_type", "type": ["null", "string"], "default": null },
    { "name": "addr1", "type": ["null", "double"], "default": null },
    { "name": "addr2", "type": ["null", "double"], "default": null },

    { "name": "payer_email_domain", "type": ["null", "string"], "default": null },
    { "name": "receiver_email_domain", "type": ["null", "string"], "default": null },

    { "name": "device_type", "type": ["null", "string"], "default": null },
    { "name": "device_info", "type": ["null", "string"], "default": null },

    { "name": "is_fraud", "type": ["null", "int"], "default": null }
  ]
}
